image: "rust:latest"

# Use cargo to test the project
test:cargo:
  script:
    - make init
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test -- --nocapture --workspace --verbose
