name: Nightly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
        target:
          - x86_64-unknown-linux-gnu
          - wasm32-unknown-unknown
    steps:
    - uses: actions/checkout@v2
    - name: Cargo Cache
      uses: actions/cache@v1
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-cargo

    - name: Cargo Target Cache
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-cargo-targe
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
        override: true
        components: rustfmt, clippy

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release ${{ matrix.target_ops }} --target ${{ matrix.target }}

    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --doc -- --test-threads 3

    - uses: actions-rs/cargo@v1
      continue-on-error: true
      with:
        command: fmt
        args: --all -- --check

    - uses: actions-rs/cargo@v1
      continue-on-error: true
      with:
        command: clippy
        args: -- -D warnings

    - name: Upload WMS Artefact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: wms-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/wms
        if-no-files-found: error
        retention-days: 90

    - name: Upload Geoconv artefact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: geoconv-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/geoconv
        if-no-files-found: error
        retention-days: 90
