[package]
authors = ["Alex <grampz@pm.me>"]
description = "Models, APIs and Tools for working with Open Geospatial Consortium (OGC) technologies"
edition = "2018"
homepage = "https://gitlab.com/atc-/ogc"
keywords = ["ogc", "geo", "map"]
license-file = "LICENSE"
name = "ogc"
readme = "../README.md"
repository = "https://gitlab.com/atc-/ogc/"
version = "0.1.0"

[dependencies]
proptest = "0.10.0"
async-traits = "0.0.0"
serde_json = "1.0.55"
anyhow = "1.0.31"
serde = "1.0.112"
serde-xml-rs = "0.4.0"
serde_derive = "1.0.112"
