[package]
authors = ["Alex Collins"]
description = "Models, APIs and Tools for working with Open Geospatial Consortium (OGC) technologies"
edition = "2018"
homepage = "https://github.com/atcol/ogc"
keywords = ["ogc", "geo", "map"]
license = "MIT"
name = "ogc"
readme = "../README.md"
repository = "https://github.com/atcol/ogc"
version = "0.6.0"

[dependencies]
async-trait = "0.1.36"
serde_json = "1.0.55"
anyhow = "1.0.31"
serde = "1.0.112"
serde-xml-rs = "0.4.0"
serde_derive = "1.0.112"
reqwest = "0.10.6"
tokio = { version = "0.2", features = ["full"] }
bytes = "0.5.5"
url = "2.1.1"
epsg = "0.1.0"
