[package]
name = "ogc"
version = "0.1.0"
authors = ["Alex <grampz@pm.me>"]
edition = "2018"

[dependencies]
proptest = "0.10.0"
async-traits = "0.0.0"
serde_json = "1.0.55"
anyhow = "1.0.31"
serde = "1.0.112"
serde-xml-rs = "0.4.0"
serde_derive = "1.0.112"
